[package]
name = "oxish-graviola"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 OR MIT"
description = "graviola crypto provider for OxiSH"
repository = "https://github.com/djc/oxish"
readme = "../README.md"
keywords = ["ssh", "protocol", "cryptography"]
categories = ["network-programming", "cryptography"]

[dependencies]
graviola = { workspace = true }
proto = { package = "oxish-proto", version = "0.2", path = "../oxish-proto" }
zeroize = { workspace = true }

[lints]
workspace = true
